Update OpenCore 0.6.4 (11/11 Compiled)
Legacy: Fix boot1 base address
OcAfterBootCompatLib: Drop legacy memory location trackers
Docs: Update changelog
DxeIpl: Fallback to 0xCF9 for reset register
OcMemoryLib: Allow overriding page allocator for allocate from top
OcAcpiLib: Relocate ACPI tables if they are not writeable (#152)
OcAfterBootCompatLib: Fix MSVC compiler moaning
OcAfterBootCompatLib: Start using call gate for kernel interception
Update Changelog.md
Docs: Fix typos
DataBase: Updated builtin firmware versions for T2 models
OpenCore: Fix load path reporting regression
OpenCore: Silence static analysis
OpenCore: Make missing tool a warning
OcBootManagementLib: Implement RealPath and TextMode for custom entries
Update SampleCustom.plist
DataBase: Updated builtin firmware versions for non-T2 models
DataBase: Revert firmware version for non-BigSur models
OcGuardLib: Avoid undefined reference to 64-bit mul builtin on IA-32
Docs: improve relative directory lookup documentation
OcGuardLib: Rely on LTO and avoid confusing macro usage
Bootstrap: Fix potential null pointer dereference
Bootstrap: Add support for launching from relative path
OcAppleKernelLib: Fix patching of injected kexts in mkext
Docs: Add Find My Mac to Sample legacy schema (#151)
Update SampleCustom.plist
BootPlatform: Add custom GraphicsConsoleDxe driver
OcBootManagementLib: Added BlacklistAppleUpdate to fix update optout
Docs: add nvram-log=1
OcAcpiLib: Add ACPI signature log printing
Bump version to 0.6.4